.PHONY: ex1 ex2

mfnet_cmd = ../../mfnet_cmd.py
ex1: 
	rm -rf results/ex1
	python $(mfnet_cmd) input_files/ex1.yaml

ex2: 
	rm -rf results/ex2
	python $(mfnet_cmd) input_files/ex2.yaml

ex3: 
	rm -rf results/ex3
	python $(mfnet_cmd) input_files/ex3.yaml

ex4: 
	rm -rf results/ex4
	python $(mfnet_cmd) input_files/ex4.yaml

ex5: 
	rm -rf results/ex5
	python $(mfnet_cmd) input_files/ex5.yaml

ex6: 
	rm -rf results/ex6
	python $(mfnet_cmd) input_files/ex6.yaml

ex7: 
	rm -rf results/ex7
	python $(mfnet_cmd) input_files/ex7.yaml

ex8: 
	rm -rf results/ex8
	python $(mfnet_cmd) input_files/ex8.yaml
