.PHONY: ex1 ex2

mfnet_cmd = ../../mfnet_cmd.py
ex1: 
	rm -rf results/ex1
	python $(mfnet_cmd) input_files/ex1.yaml

ex2: 
	rm -rf results/ex2
	python $(mfnet_cmd) input_files/ex2.yaml

ex3: 
	rm -rf results/ex3
	python $(mfnet_cmd) input_files/ex3.yaml
